version: '3.3'
services:
  app:
    build: .
    restart: always
    env_file: booked.env
    ports: 
       - '8080:80'
    volumes:
      - ./uploads:/var/www/booked/uploads
      - ./Web/uploads:/var/www/booked/Web/uploads
      - ./Web/img:/var/www/booked/Web/img
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    env_file: mysql.env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
volumes:
  data:
